# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 15:44
from __future__ import unicode_literals

import cache_machine.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankClient',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('card_number', models.BigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='card number')),
                ('full_name', models.CharField(max_length=255, verbose_name='full name')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('balance', models.BigIntegerField(default=0, verbose_name='balance')),
                ('login_fail_count', models.SmallIntegerField(default=0, verbose_name='login fail count')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'bank client',
                'verbose_name_plural': 'bank clients',
            },
            managers=[
                ('objects', cache_machine.models.BankUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ClientAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SmallIntegerField(verbose_name='action code')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='action time')),
                ('value', models.BigIntegerField(verbose_name='action value')),
                ('bank_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'client action',
                'verbose_name_plural': 'client actions',
            },
        ),
    ]
